* 기존의 입력데이터였던 1차원벡터 X=[1,2,3]을 2차원 벡터X=[ [1,2] , [3,4] ]으로 수정한 채로 코드를 입력했습니다.
* 기존의 출력데이터였던 1차원 벡터 x=[1,2,3]은 1차원 벡터Y=[5,6]으로 수정하였습니다.

In [1]:
from google.colab import drive
drive.mount("/gdrive", force_remount=True)

Mounted at /gdrive


In [28]:
import numpy as np
import torch

# 데이터 읽기 함수
def load_dataset(file):
    data = np.loadtxt(file)
    print(f'수정한 데이터 DATA=\n{data}\n')

    # X에 입력 데이터, Y에 출력 데이터를 저장
    x = data[:,0:-1]  # 모든 행, 0열부터 마지막 열 직전 열
    print(f'입력데이터 x=\n{x}\n')

    y = np.reshape(data[:,-1],(data.shape[0], 1))  # 모든 행, 마지막 열을 가져오고, (2,1)로 재배열
    print(f'출력데이터 y=\n{y}\n')

    # 텐서로 변경
    x = torch.tensor(x, dtype=torch.float32)  # 입력 데이터를 텐서로 변환
    y = torch.tensor(y, dtype=torch.float32)  # 출력 데이터를 텐서로 변환

    return x, y

# 텐서를 리스트로 바꾸는 함수
def tensor2list(input_tensor):
    return input_tensor.cpu().detach().numpy().tolist()

# 데이터 불러오기
x, y = load_dataset("/gdrive/My Drive/ML/train2.txt")

# 가중치 초기화 (입력 데이터의 차원이 2이므로 가중치도 2개로 초기화)
w = torch.randn(x.size(1)) * 3.0  # x.size(1)은 입력 데이터의 열 개수
print("초기: w = {0}\n".format(tensor2list(w)))

# 학습률
alpha = 0.1

# 학습 데이터 수
m = y.size(0)

# 학습 루프
for epoch in range(50):
    cost = 0
    for i in range(m):
        # 가중치와 입력의 내적을 이용해 예측 값 계산
        cost = cost + ((torch.dot(w, x[i]) - y[i]) * x[i])
    cost = 1 / m * cost
    w = w - alpha * cost  # 가중치 업데이트

    # 학습 중 가중치 값 출력
    w1, w2 = tensor2list(w)[0], tensor2list(w)[1]
    print(f"Epoch {epoch + 1}: w1 = {w1}, w2 = {w2}")


수정한 데이터 DATA=
[[1. 2. 5.]
 [3. 4. 6.]]

입력데이터 x=
[[1. 2.]
 [3. 4.]]

출력데이터 y=
[[5.]
 [6.]]

초기: w = [-2.3304409980773926, 1.9450876712799072]

Epoch 1: w1 = -1.3767818212509155, w2 = 3.3313088417053223
Epoch 2: w1 = -1.870307207107544, w2 = 2.6637473106384277
Epoch 3: w1 = -1.6497766971588135, w2 = 3.0092151165008545
Epoch 4: w1 = -1.7813389301300049, w2 = 2.854843854904175
Epoch 5: w1 = -1.7390601634979248, w2 = 2.946937322616577
Epoch 6: w1 = -1.782386302947998, w2 = 2.917341947555542
Epoch 7: w1 = -1.7833324670791626, w2 = 2.9476704597473145
Epoch 8: w1 = -1.8050355911254883, w2 = 2.9483327865600586
Epoch 9: w1 = -1.8163506984710693, w2 = 2.96352481842041
Epoch 10: w1 = -1.8326427936553955, w2 = 2.9714455604553223
Epoch 11: w1 = -1.8463332653045654, w2 = 2.9828500747680664
Epoch 12: w1 = -1.861161708831787, w2 = 2.9924333095550537
Epoch 13: w1 = -1.875284194946289, w2 = 3.0028131008148193
Epoch 14: w1 = -1.8896112442016602, w2 = 3.0126988887786865
Epoch 15: w1 = -1.9036948680877686,