* 기존의 입력데이터였던 1차원벡터 X=[1,2,3]을 2차원 벡터X=[ [1,2] , [4,1], [3,5] ]으로 수정한 채로 코드를 입력했습니다.
* 기존의 출력데이터였던 1차원 벡터 x=[1,2,3]은 1차원 벡터Y=[3,5,8]으로 수정하였습니다.

In [1]:
from google.colab import drive
drive.mount("/gdrive", force_remount=True)

Mounted at /gdrive


* w가 [1,0, 1.0]에 수렴하도록 하는 것이 목표

In [21]:
import numpy as np
import torch

# 데이터 읽기 함수
def load_dataset(file):
    data = np.loadtxt(file)
    print(f'수정한 데이터 DATA=\n{data}\n')

    # X에 입력 데이터, Y에 출력 데이터를 저장
    x = data[:,0:-1]  # 모든 행, 0열부터 마지막 열 직전 열
    print(f'입력데이터 x=\n{x}\n')

    y = np.reshape(data[:,-1],(data.shape[0], 1))  # 모든 행, 마지막 열을 가져오고, (2,1)로 재배열
    print(f'출력데이터 y=\n{y}\n')

    # 텐서로 변경
    x = torch.tensor(x, dtype=torch.float32)  # 입력 데이터를 텐서로 변환
    y = torch.tensor(y, dtype=torch.float32)  # 출력 데이터를 텐서로 변환

    return x, y

# 텐서를 리스트로 바꾸는 함수
def tensor2list(input_tensor):
    return input_tensor.cpu().detach().numpy().tolist()

# 데이터 불러오기
x, y = load_dataset("/gdrive/My Drive/ML/train2.txt")

# 가중치 초기화 (입력 데이터의 차원이 2이므로 가중치도 2개로 초기화)
w = torch.randn(x.size(1)) * 3.0  # x.size(1)은 입력 데이터의 열 개수
print("초기: w = {0}\n".format(tensor2list(w)))

# 학습률
alpha = 0.1

# 학습 데이터 수
m = y.size(0)

# 학습 루프
for epoch in range(100):
    cost = 0
    for i in range(m):
        # 가중치와 입력의 내적을 이용해 예측 값 계산
        cost = cost + ((torch.dot(w, x[i]) - y[i]) * x[i])
    cost = 1 / m * cost
    w = w - alpha * cost  # 가중치 업데이트

    # 학습 중 가중치 값 출력
    print(f"Epoch {epoch + 1}: w = {tensor2list(w)}")
    w1=tensor2list(w)[0]
    w2=tensor2list(w)[1]
    if w1==1.0 and w2==1.0:
      break


수정한 데이터 DATA=
[[1. 2. 3.]
 [4. 1. 5.]
 [3. 5. 8.]]

입력데이터 x=
[[1. 2.]
 [4. 1.]
 [3. 5.]]

출력데이터 y=
[[3.]
 [5.]
 [8.]]

초기: w = [-1.5606324672698975, -5.203533172607422]

Epoch 1: w = [5.001055717468262, 2.79244327545166]
Epoch 2: w = [0.2787632942199707, -1.8007392883300781]
Epoch 3: w = [2.8643527030944824, 1.5048656463623047]
Epoch 4: w = [0.8951742649078369, -0.3050469160079956]
Epoch 5: w = [1.8995561599731445, 1.073378086090088]
Epoch 6: w = [1.0685760974884033, 0.37031060457229614]
Epoch 7: w = [1.4499260187149048, 0.9519967436790466]
Epoch 8: w = [1.0935922861099243, 0.685051679611206]
Epoch 9: w = [1.232942819595337, 0.9344853758811951]
Epoch 10: w = [1.0769193172454834, 0.8369401097297668]
Epoch 11: w = [1.1243977546691895, 0.9461564421653748]
Epoch 12: w = [1.0542768239974976, 0.9129216074943542]
Epoch 13: w = [1.0681917667388916, 0.9620062112808228]
Epoch 14: w = [1.0356879234313965, 0.952265739440918]
Epoch 15: w = [1.0381723642349243, 0.9750184416770935]
Epoch 16: w = [1.0